sysdesign:
  git_url: "https://github.com/TechMaster/sysdesign"
  git_folder: "/Users/cuong/CODE/gohugo/sysdesign"
  minify_folder: "/Users/cuong/CODE/gohugo/minify"
learnphp:
  git_url: "https://github.com/TechMaster/learnphp"
  git_folder: "/Users/cuong/CODE/gohugo/learnphp"
  minify_folder: "/Users/cuong/CODE/gohugo/minify_php"